name: hola-mundo #Nombre del workflow
on: [push] #Evento que lo activar치
jobs: #Definici칩n de los jobs
  imprimir-hola-mundo: #Nombre del job
    runs-on: ubuntu-latest #Maquina en la que correr치
    steps: #Lista de steps del job hola-mundo
      - name: Public IP #Nombre del primer step
        id: ip #identificador usable dentro del job para otros steps
        uses: haythem/public-ip@v1.3 #Usar치 el action haythem/public-ip
      - name: Hola mundo #Nombre del segundo step
        run: echo Hola Mundo desde ${{ steps.ip.outputs.ipv4 }}! #comando de bash
      - uses: actions/checkout@v3
      - name: configurar Go #Nombre del tercer step
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - name: Construir y ejecutra el programa en Go #Nombre del cuarto step
        run: |
          go build -o hola-mundo main.go
          ./hola-mundo